dist: trusty
sudo: false
language: cpp

compiler: g++
install: export CXX="g++-6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - valgrind

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get update

script:
  - ./travis.sh

after_success:
  - coveralls --root . \
    -E ".*CMakeFiles.*" \
    -e gtest/ \
    -e tests/ \
    -e examples/
